# Generated by Django 3.1.1 on 2020-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201004_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_MidRes',
            field=models.ImageField(blank=True, upload_to='MidRes'),
        ),
    ]
