# Generated by Django 3.1.1 on 2020-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201011_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
