# Generated by Django 3.1.1 on 2020-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_name',
            field=models.TextField(default='Kuva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(max_length=25),
        ),
    ]
