# Generated by Django 3.1.1 on 2020-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20201012_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=25),
        ),
    ]
