# Generated by Django 3.1.1 on 2020-10-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_photogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.photogroup'),
        ),
    ]
