# Generated by Django 3.1.1 on 2020-10-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_photo_photo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='upload.photogroup'),
        ),
    ]
