# Generated by Django 3.1.1 on 2020-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20201013_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
