# Generated by Django 3.1.1 on 2020-10-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_photo_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
