# Generated by Django 3.1.1 on 2020-10-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20201014_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded',
            field=models.DateTimeField(),
        ),
    ]
